"""WAF / IPS fingerprinting.

Sends a deliberately noisy injection probe and looks for well-known product
signatures in the status, headers, and body. This is detection only — it does
not try to bypass anything; the scanner's tamper chain is the evasion half.
"""

from __future__ import annotations

from dataclasses import dataclass

from .http_client import HttpClient
from .target import Target

# (product, where, needle) — needles are matched case-insensitively.
_HEADER_SIGS: list[tuple[str, str]] = [
    ("Cloudflare", "cf-ray"),
    ("Cloudflare", "cf-mitigated"),
    ("AWS WAF", "x-amzn-waf"),
    ("AWS WAF", "x-amzn-requestid"),
    ("Akamai", "x-akamai-transformed"),
    ("Akamai", "akamai-origin-hop"),
    ("Imperva / Incapsula", "x-iinfo"),
    ("Imperva / Incapsula", "x-cdn"),
    ("Sucuri", "x-sucuri-id"),
    ("Sucuri", "x-sucuri-block"),
    ("F5 BIG-IP ASM", "x-cnection"),
    ("F5 BIG-IP ASM", "x-wa-info"),
    ("Barracuda", "barra_counter_session"),
    ("Wordfence", "x-wordfence"),
    ("ModSecurity", "mod_security"),
    ("Azure Front Door / WAF", "x-azure-ref"),
]

_BODY_SIGS: list[tuple[str, str]] = [
    ("Cloudflare", "attention required! | cloudflare"),
    ("Cloudflare", "cf-error-details"),
    ("Cloudflare", "cloudflare ray id"),
    ("AWS WAF", "request blocked"),
    ("AWS WAF", "generated by cloudfront"),
    ("Akamai", "access denied"),
    ("Akamai", "reference #"),
    ("Imperva / Incapsula", "incapsula incident id"),
    ("Imperva / Incapsula", "_incapsula_resource"),
    ("Sucuri", "sucuri website firewall"),
    ("Sucuri", "access denied - sucuri"),
    ("ModSecurity", "mod_security"),
    ("ModSecurity", "this error was generated by mod_security"),
    ("Wordfence", "generated by wordfence"),
    ("Wordfence", "a potentially unsafe operation has been detected"),
    ("F5 BIG-IP ASM", "the requested url was rejected"),
    ("F5 BIG-IP ASM", "support id:"),
    ("Barracuda", "barracuda"),
    ("FortiWeb", "fortiweb"),
    ("Citrix NetScaler", "ns_app_fw"),
    ("Generic WAF", "web application firewall"),
    ("Generic WAF", "your request has been blocked"),
    ("Generic WAF", "not acceptable"),
]

# Classic noisy probe: quote + tautology + UNION + comment. Many WAFs
# signature-match this exact shape.
_NOISY_PROBE = "1' AND 1=1 UNION SELECT NULL,NULL,NULL--"


@dataclass
class WafResult:
    detected: bool
    product: str = ""
    evidence: str = ""
    status_code: int = 0

    def to_dict(self) -> dict:
        return {
            "detected": self.detected,
            "product": self.product,
            "evidence": self.evidence,
            "status_code": self.status_code,
        }


def _match_headers(headers: dict) -> tuple[str, str] | None:
    lowered = {str(k).lower(): str(v) for k, v in headers.items()}
    for product, needle in _HEADER_SIGS:
        for name, value in lowered.items():
            if needle in name or needle in value.lower():
                return product, f"header {name}: {value[:80]}"
    return None


def _match_body(text: str) -> tuple[str, str] | None:
    blob = (text or "").lower()
    for product, needle in _BODY_SIGS:
        if needle in blob:
            return product, f"body contained {needle!r}"
    return None


async def detect_waf(client: HttpClient, target: Target) -> WafResult:
    """Probe ``target`` with a noisy payload and fingerprint any WAF."""
    param = next(iter(target.params), None)
    if param is None:
        # No injectable-looking param: hit the URL as-is and still read headers.
        resp = await client.request(
            target.method, target.url, cookies=target.cookies
        )
        value = ""
    else:
        base = target.params.get(param, "")
        value = f"{base}{_NOISY_PROBE}"
        params = target.mutate(param, value)
        if target.is_get():
            resp = await client.request(
                target.method, target.url, params=params, cookies=target.cookies
            )
        else:
            resp = await client.request(
                target.method, target.url, data=params, cookies=target.cookies
            )

    header_hit = _match_headers(resp.headers)
    if header_hit:
        product, evidence = header_hit
        return WafResult(True, product, evidence, resp.status_code)

    body_hit = _match_body(resp.text)
    if body_hit:
        product, evidence = body_hit
        return WafResult(True, product, evidence, resp.status_code)

    if resp.status_code in {403, 406, 419, 429, 503} and param is not None:
        return WafResult(
            True,
            "Generic WAF / filter",
            (
                f"noisy probe returned HTTP {resp.status_code} "
                f"(payload {value!r})"
            ),
            resp.status_code,
        )

    return WafResult(False, status_code=resp.status_code)
